Ensemble hard-voting

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install konlpy

Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
     |████████████████████████████████| 19.4 MB 1.2 MB/s
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (4.2.6)
Collecting JPype1>=0.7.0
  Downloading JPype1-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (448 kB)
     |████████████████████████████████| 448 kB 50.7 MB/s
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.21.5)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (4.1.1)
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.3.0 konlpy-0.6.0

In [29]:
import pandas as pd

a = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLP/projects/project2/kaggle/dump/ensemble/v2/KoBigBird_check_V2(2.37).csv')
a = a.drop(['Context', 'Question'], axis=1)
#a = a.drop(0, axis=0)
#a = a.rename(columns={'Predicted':'Predicted_a', 'levenshtein':'levenshtein_a'})
a

,Predicted,Start,End,Score,guid,Answer,Id,levenshtein,Answer_length
0,뉴 740Li 25주년 에디션,666.0,682.0,0.637650,klue-mrc-v1_dev_01891,"['뉴 740Li 25주년 에디션', '뉴 740Li 25주년']",d14cb73158624cf094c546d856fd3c80,0,16.0
1,독일 뒤셀도르프,556.0,565.0,0.725427,klue-mrc-v1_dev_01842,['독일 뒤셀도르프'],906631384e91493ebe1c7f34aea6f241,0,9.0
2,페이스북,543.0,548.0,0.556682,klue-mrc-v1_dev_02673,['페이스북'],35e61dcb479643448a2cb7d326ae50a6,0,5.0
3,페이스북,543.0,548.0,0.500647,klue-mrc-v1_dev_05664,['페이스북'],075e761b370040cb9041eecd39afc27c,0,5.0
4,마드리드,408.0,413.0,0.998218,klue-mrc-v1_dev_00170,['마드리드'],e67ed38f3dd944be94d5b4c53731f334,0,5.0
...,...,...,...,...,...,...,...,...,...
4004,2만달러,546.0,551.0,0.242327,klue-mrc-v1_dev_03796,['200만엔'],05fcb8054dc44dab8683579c2cf5e465,4,5.0
4005,중동 건설 현장,470.0,480.0,0.512491,klue-mrc-v1_dev_00770,"['중동 건설 현장', '중동']",cc7f826b66724ce9b39e3a974ca15661,0,10.0
4006,아시아~유럽 노선,383.0,393.0,0.589738,klue-mrc-v1_dev_04893,"['아시아~유럽 노선', '아시아~유럽']",3282034aa41e4fab980851ffd4a868dd,0,10.0
4007,사흘간,313.0,316.0,0.602099,klue-mrc-v1_dev_04183,['사흘'],0a73550b36df4baf82ac2f98619d22e7,1,3.0
4008,벨기,158.0,161.0,0.992031,klue-mrc-v1_dev_03199,['벨기에'],dfe6ef25f84f461e89e54d370e4521d5,1,3.0

In [20]:
b = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLP/projects/project2/kaggle/dump/ensemble/v2/koelectra-base-v3-finetuned-korquad_check_V2(3.25).csv')
b = b.drop(['Context', 'Question', 'guid','levenshtein'], axis=1)
#b = b.rename(columns={'Predicted':'Predicted_b'})
b

,Predicted,Start,End,Score,Answer,Id,Answer_length
0,뉴 740Li 25주년 에디션,682,0.999931,NaN,"['뉴 740Li 25주년 에디션', '뉴 740Li 25주년']",d14cb73158624cf094c546d856fd3c80,16.0
1,독일 뒤셀도르프,565,0.999421,NaN,['독일 뒤셀도르프'],906631384e91493ebe1c7f34aea6f241,9.0
2,링크트인과 페이스북,548,0.999889,NaN,['페이스북'],35e61dcb479643448a2cb7d326ae50a6,11.0
3,링크트인과 페이스북,548,0.999581,NaN,['페이스북'],075e761b370040cb9041eecd39afc27c,11.0
4,마드리드,413,0.999999,NaN,['마드리드'],e67ed38f3dd944be94d5b4c53731f334,5.0
...,...,...,...,...,...,...,...
4004,2만달러,551,0.220239,NaN,['200만엔'],05fcb8054dc44dab8683579c2cf5e465,5.0
4005,중동 건설 현장,480,0.999990,NaN,"['중동 건설 현장', '중동']",cc7f826b66724ce9b39e3a974ca15661,10.0
4006,유럽 노선,1595,0.999992,NaN,"['아시아~유럽 노선', '아시아~유럽']",3282034aa41e4fab980851ffd4a868dd,7.0
4007,사흘간,316,0.964262,NaN,['사흘'],0a73550b36df4baf82ac2f98619d22e7,3.0
4008,벨기,161,0.757934,NaN,['벨기에'],dfe6ef25f84f461e89e54d370e4521d5,3.0

In [21]:
c = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLP/projects/project2/kaggle/dump/ensemble/koelectra-base-v3-discriminator-finetuned-klue_check(3.46).csv')
c = c.drop(['Context', 'Question', 'guid','levenshtein'], axis=1)
#c = c.rename(columns={'Predicted':'Predicted_b'})
c

,Predicted,Start,End,Score,Answer,Id
0,뉴 740Li 25주년 에디션,666.0,682.0,0.103343,"['뉴 740Li 25주년 에디션', '뉴 740Li 25주년']",d14cb73158624cf094c546d856fd3c80
1,뒤셀도르프,559.0,565.0,0.572797,['독일 뒤셀도르프'],906631384e91493ebe1c7f34aea6f241
2,꾸준히,1071.0,1074.0,0.981770,['페이스북'],35e61dcb479643448a2cb7d326ae50a6
3,꾸준히,1071.0,1074.0,0.983212,['페이스북'],075e761b370040cb9041eecd39afc27c
4,마드리드,408.0,413.0,0.980107,['마드리드'],e67ed38f3dd944be94d5b4c53731f334
...,...,...,...,...,...,...
4004,2만달러로,546.0,551.0,0.118583,['200만엔'],05fcb8054dc44dab8683579c2cf5e465
4005,중동 건설 현장,470.0,480.0,0.677122,"['중동 건설 현장', '중동']",cc7f826b66724ce9b39e3a974ca15661
4006,아시아~유럽,383.0,389.0,0.535192,"['아시아~유럽 노선', '아시아~유럽']",3282034aa41e4fab980851ffd4a868dd
4007,12일까지,988.0,993.0,0.612616,['사흘'],0a73550b36df4baf82ac2f98619d22e7
4008,벨기에,158.0,161.0,0.714576,['벨기에'],dfe6ef25f84f461e89e54d370e4521d5

In [22]:
d = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLP/projects/project2/kaggle/dump/ensemble/v2/xlm-roberta-base_check_V2(3.49).csv')
d = d.drop(['Context', 'Question', 'guid','levenshtein'], axis=1)
#d = d.rename(columns={'Predicted':'Predicted_b'})
d

,Predicted,Start,End,Score,Answer,Id,Answer_length
0,뉴 740Li 25주년 에디션(7,666.0,685.0,0.424860,"['뉴 740Li 25주년 에디션', '뉴 740Li 25주년']",d14cb73158624cf094c546d856fd3c80,19.0
1,뒤셀도르프,559.0,565.0,0.303050,['독일 뒤셀도르프'],906631384e91493ebe1c7f34aea6f241,6.0
2,베인&컴퍼니,196.0,203.0,0.422743,['페이스북'],35e61dcb479643448a2cb7d326ae50a6,7.0
3,베인&컴퍼니,196.0,203.0,0.439489,['페이스북'],075e761b370040cb9041eecd39afc27c,7.0
4,마드리드,408.0,413.0,0.952330,['마드리드'],e67ed38f3dd944be94d5b4c53731f334,5.0
...,...,...,...,...,...,...,...
4004,4만달러,539.0,545.0,0.325296,['200만엔'],05fcb8054dc44dab8683579c2cf5e465,6.0
4005,중동 건설 현장,470.0,480.0,0.912075,"['중동 건설 현장', '중동']",cc7f826b66724ce9b39e3a974ca15661,10.0
4006,아시아~유럽 노선,383.0,393.0,0.799744,"['아시아~유럽 노선', '아시아~유럽']",3282034aa41e4fab980851ffd4a868dd,10.0
4007,사흘간,313.0,316.0,0.427263,['사흘'],0a73550b36df4baf82ac2f98619d22e7,3.0
4008,벨기,158.0,161.0,0.905652,['벨기에'],dfe6ef25f84f461e89e54d370e4521d5,3.0

In [23]:
e = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLP/projects/project2/kaggle/dump/ensemble/bert-base-multilingual-cased_check(3.78).csv')
e = e.drop(['Context', 'Question', 'guid','levenshtein'], axis=1)
#e = e.rename(columns={'Predicted':'Predicted_b'})
e

,Predicted,Start,End,Score,Answer,Id
0,뉴 520d 25주년 에디션,471.0,486.0,0.109872,"['뉴 740Li 25주년 에디션', '뉴 740Li 25주년']",d14cb73158624cf094c546d856fd3c80
1,프랑스 남부 알프스,0.0,11.0,0.402391,['독일 뒤셀도르프'],906631384e91493ebe1c7f34aea6f241
2,페이스북,543.0,548.0,0.243654,['페이스북'],35e61dcb479643448a2cb7d326ae50a6
3,링크트인,537.0,542.0,0.268323,['페이스북'],075e761b370040cb9041eecd39afc27c
4,마드리드,408.0,413.0,0.979894,['마드리드'],e67ed38f3dd944be94d5b4c53731f334
...,...,...,...,...,...,...
4004,4만달러에서,539.0,545.0,0.102690,['200만엔'],05fcb8054dc44dab8683579c2cf5e465
4005,중동 건설 현장,470.0,480.0,0.654978,"['중동 건설 현장', '중동']",cc7f826b66724ce9b39e3a974ca15661
4006,아시아~유럽 노선,383.0,393.0,0.622451,"['아시아~유럽 노선', '아시아~유럽']",3282034aa41e4fab980851ffd4a868dd
4007,사흘간,393.0,396.0,0.838193,['사흘'],0a73550b36df4baf82ac2f98619d22e7
4008,미국,109.0,113.0,0.915964,['벨기에'],dfe6ef25f84f461e89e54d370e4521d5

In [46]:
a['Id'][1]

'906631384e91493ebe1c7f34aea6f241'

In [50]:
import numpy as np
import pandas as pd

model_weight=[0.4, 0.2, 0.15, 0.15, 0.1]

result = {'Id':[], 'Answer':[], 'Predicted':[]}

for j in range(4009):
    score = [0.0, 0.0, 0.0, 0.0, 0.0]
    predicts = [a['Predicted'][j],b['Predicted'][j],c['Predicted'][j],d['Predicted'][j],e['Predicted'][j]]
    pass_ = []

    predicts = np.array(predicts)
    for i in range(len(predicts)):
        pos = np.where(predicts == predicts[i])[0]
        sum = 0.0
        for p in pos:
            if p in pass_:
                continue
            pass_.append(p)
            sum += model_weight[p]
        for p in pos:
            score[p] += sum

    result['Id'].append(a['Id'][j])
    result['Answer'].append(a['Answer'][j])
    result['Predicted'].append(predicts[score.index(max(score))]) 

result_df = pd.DataFrame(result)
result_df

,Id,Answer,Predicted
0,d14cb73158624cf094c546d856fd3c80,"['뉴 740Li 25주년 에디션', '뉴 740Li 25주년']",뉴 740Li 25주년 에디션
1,906631384e91493ebe1c7f34aea6f241,['독일 뒤셀도르프'],독일 뒤셀도르프
2,35e61dcb479643448a2cb7d326ae50a6,['페이스북'],페이스북
3,075e761b370040cb9041eecd39afc27c,['페이스북'],페이스북
4,e67ed38f3dd944be94d5b4c53731f334,['마드리드'],마드리드
...,...,...,...
4004,05fcb8054dc44dab8683579c2cf5e465,['200만엔'],2만달러
4005,cc7f826b66724ce9b39e3a974ca15661,"['중동 건설 현장', '중동']",중동 건설 현장
4006,3282034aa41e4fab980851ffd4a868dd,"['아시아~유럽 노선', '아시아~유럽']",아시아~유럽 노선
4007,0a73550b36df4baf82ac2f98619d22e7,['사흘'],사흘간
4008,dfe6ef25f84f461e89e54d370e4521d5,['벨기에'],벨기

In [51]:
result_df.to_csv('/content/drive/MyDrive/Colab Notebooks/NLP/projects/project2/kaggle/dump/ensemble/result/result_weight.csv')